#!/bin/sh
cd /home/ec2-user/cs502-b/play-big-data/kafka
python flask-data-producer.py >/tmp/log1 2>&1 &
cd /home/ec2-user/cs502-b/play-big-data/spark
spark-submit --jars spark-streaming-kafka-0-8-assembly_2.11-2.0.0.jar stream-processing.py stock-analyzer averages-stock-price 127.0.0.1:9092 >/tmp/log2 2>&1 &
cd /home/ec2-user/cs502-b/play-big-data/redis
python redis-publisher.py averages-stock-price 127.0.0.1:9092 averages-stock-price 127.0.0.1 6379 >/tmp/log3 2>&1 &
cd /home/ec2-user/cs502-b/play-big-data/nodejs
node index.js --port=3000 --redis_host=127.0.0.1 redis_port=6379 --subscribe_topic=averages-stock-price >/tmp/log4 2>&1 &
